---
id: github-actions-osaka-meetup-osaka-1
base_name: workflow-job-step
tags:
- github
presentation_date: 2019/11/26
version: 2019.11.26
licenses: []
slideshare_id: workflowjobstep
speaker_deck_id: workflow-job-step-falseshi-ifen-kefalseji-zhun-wokao-eru
ustream_id:
vimeo_id:
youtube_id:
author:
  markup_language: :markdown
  name: Kazuhiro NISHIYAMA
  email: zn@mbf.nifty.com
  rubygems_user: znz
  slideshare_user: znzjp
  speaker_deck_user: znz
